export enum Resources {
  // ---- SPRITES ----

  Background = 'background',
  IndicatorLight = 'IndicatorLight',
  IndicatorLightColor = 'IndicatorLightColor',
  TileShape = 'TileShape',
  TileFill = 'TileFill',
  TileNumber1 = 'TileNumber1',
  TileNumber2 = 'TileNumber2',
  TileNumber3 = 'TileNumber3',
  TileNumber4 = 'TileNumber4',
  TileNumber5 = 'TileNumber5',
  TileNumber6 = 'TileNumber6',
  TileNumber7 = 'TileNumber7',
  TileNumber8 = 'TileNumber8',
  Shadow = 'shadow',
  GhostSpritesheet = 'GhostSpritesheet',

  // ---- SOUNDS ----

  ValidatePath = 'validatePath',
  FailPath = 'failPath',
  Block = 'Block',

  // ---- MUSIC ----

  // Hub
  hub_bg = 'hub_bg',
  hub_ccl_flutes = 'hub_ccl_flutes',
  hub_cd_organ = 'hub_cd_organ',
  hub_cls_accordion = 'hub_cls_accordion',
  hub_cl_violin = 'hub_cl_violin',
  hub_c_piano = 'hub_c_piano',
  hub_d_chirp = 'hub_d_chirp',
  hub_sd_bells = 'hub_sd_bells',
  hub_s_harp = 'hub_s_harp',
  hub_celtic_clue = 'hub_celtic_clue',

  // City
  city_bg = 'city_bg',
  city_A_melody_cello = 'city_A_melody_cello',
  city_A_melody_marimba = 'city_A_melody_marimba',
  city_A_melody_piano_f = 'city_A_melody_piano_f',
  city_A_melody_piano_p = 'city_A_melody_piano_p',
  city_A_melody_vibra = 'city_A_melody_vibra',
  city_A_melody_violin = 'city_A_melody_violin',
  city_chord_A = 'city_chord_A',
  city_chord_F = 'city_chord_F',
  city_chord_G = 'city_chord_G',
  city_D_melody_cello = 'city_D_melody_cello',
  city_D_melody_ethan = 'city_D_melody_ethan',
  city_D_melody_piano = 'city_D_melody_piano',
  city_D_melody_violins = 'city_D_melody_violins',
  city_F_melody_ethan = 'city_F_melody_ethan',
  city_F_melody_piano_1 = 'city_F_melody_piano_1',
  city_F_melody_piano_2 = 'city_F_melody_piano_2',
  city_F_melody_piano_3 = 'city_F_melody_piano_3',
  city_F_melody_vibra = 'city_F_melody_vibra',
  city_marimba_bg_CA = 'city_marimba_bg_CA',
  city_marimba_bg_F = 'city_marimba_bg_F',
  city_marimba_bg_G = 'city_marimba_bg_G',
  city_marimba_rtm_A = 'city_marimba_rtm_A',
  city_marimba_rtm_F_2 = 'city_marimba_rtm_F_2',
  city_piano_rtm_F_2 = 'city_piano_rtm_F_2',
  city_piano_rtm_F = 'city_piano_rtm_F',
  city_violin_bg_D = 'city_violin_bg_D',
  city_violin_bg_F = 'city_violin_bg_F',
  city_violin_bg_GA = 'city_violin_bg_GA',
  city_violins_rtm_D = 'city_violins_rtm_D',
  city_winds_E_p = 'city_winds_E_p',
  city_winds_E_w = 'city_winds_E_w',
  city_winds_FG = 'city_winds_FG',
  city_winds_GE_p = 'city_winds_GE_p',
  city_winds_GE_w = 'city_winds_GE_w',
  city_xylophone_rtm_F_2 = 'city_xylophone_rtm_F_2',
  city_xylophone_rtm_F = 'city_xylophone_rtm_F',
  city_xylo_rtm_A = 'city_xylo_rtm_A',

  // Celtic
  celtic_bg = 'celtic_bg',
  celtic_A_bagpipe = 'celtic_A_bagpipe',
  celtic_A_bombarde = 'celtic_A_bombarde',
  celtic_A_perc = 'celtic_A_perc',
  celtic_A_tenor = 'celtic_A_tenor',
  celtic_A2_bagpipe = 'celtic_A2_bagpipe',
  celtic_A2_bombarde = 'celtic_A2_bombarde',
  celtic_A2_bourdons = 'celtic_A2_bourdons',
  celtic_B_bagad = 'celtic_B_bagad',
  celtic_B_bombarde = 'celtic_B_bombarde',
  celtic_B_cornemuse = 'celtic_B_cornemuse',
  celtic_B_tenor = 'celtic_B_tenor',
  celtic_B_whistle = 'celtic_B_whistle',
  celtic_B_guitar = 'celtic_B_guitar',
  celtic_B_koto = 'celtic_B_koto',
  celtic_B_violin = 'celtic_B_violin',
  celtic_C_whistle = 'celtic_C_whistle',
  celtic_C_guitar_chords = 'celtic_C_guitar_chords',
  celtic_C_guitar = 'celtic_C_guitar',
  celtic_C_harp = 'celtic_C_harp',
  celtic_C_violin = 'celtic_C_violin',
  celtic_C_whistle_high = 'celtic_C_whistle_high',
  celtic_C_ocarina = 'celtic_C_ocarina',

  // Sea
  sea_bg = 'sea_bg',
  sea_A_bass = 'sea_A_bass',
  sea_A_bells = 'sea_A_bells',
  sea_A_marimbas = 'sea_A_marimbas',
  sea_A_piano = 'sea_A_piano',
  sea_A_string = 'sea_A_string',
  sea_A_whistle = 'sea_A_whistle',
  sea_A_winds = 'sea_A_winds',
  sea_A_chimes = 'sea_A_chimes',
  sea_B_comet = 'sea_B_comet',
  sea_B_guitars = 'sea_B_guitars',
  sea_B_voyager = 'sea_B_voyager',
  sea_B_flute = 'sea_B_flute',
  sea_B_synth = 'sea_B_synth',
  sea_C_cornemuse = 'sea_C_cornemuse',
  sea_C_guitar = 'sea_C_guitar',
  sea_C_oboe = 'sea_C_oboe',
  sea_C_timpanis = 'sea_C_timpanis',
  sea_C_cymbals = 'sea_C_cymbals',
  sea_C_horn = 'sea_C_horn',
  sea_C_strings = 'sea_C_strings',
  sea_C_violin = 'sea_C_violin',

  // Desert
  desert_bg = 'desert_bg',
  desert_A_chords = 'desert_A_chords',
  desert_A_drums = 'desert_A_drums',
  desert_A_rhodes = 'desert_A_rhodes',
  desert_B_drum = 'desert_B_drum',
  desert_B_piano = 'desert_B_piano',
  desert_B_terje = 'desert_B_terje',
  desert_B_synth = 'desert_B_synth',
  desert_C_bells = 'desert_C_bells',
  desert_C_marimba = 'desert_C_marimba',
  desert_C_sax = 'desert_C_sax',
  desert_flute = 'desert_flute',
}

export const images = new Map<Resources, string>([
  [Resources.Background, 'assets/sprites/background.png'],
  [Resources.IndicatorLight, 'assets/sprites/light_base.png'],
  [Resources.IndicatorLightColor, 'assets/sprites/light_color.png'],
  [Resources.TileShape, 'assets/sprites/tiles/tile_shape.png'],
  [Resources.TileFill, 'assets/sprites/tiles/tile_fill.png'],
  [Resources.TileNumber1, 'assets/sprites/tiles/tile_number_1.png'],
  [Resources.TileNumber2, 'assets/sprites/tiles/tile_number_2.png'],
  [Resources.TileNumber3, 'assets/sprites/tiles/tile_number_3.png'],
  [Resources.TileNumber4, 'assets/sprites/tiles/tile_number_4.png'],
  [Resources.TileNumber5, 'assets/sprites/tiles/tile_number_5.png'],
  [Resources.TileNumber6, 'assets/sprites/tiles/tile_number_6.png'],
  [Resources.TileNumber7, 'assets/sprites/tiles/tile_number_7.png'],
  [Resources.TileNumber8, 'assets/sprites/tiles/tile_number_8.png'],
  [Resources.Shadow, 'assets/sprites/ghost/shadow.png'],
]);

export const sprites = new Map<Resources, string>([
  [Resources.GhostSpritesheet, 'assets/sprites/ghost/ghost_spritesheet.png'],
]);

export const sounds = new Map<Resources, string>([
  [Resources.ValidatePath, 'assets/sounds/tubular_bells.wav'],
  [Resources.FailPath, 'assets/sounds/fail.wav'],
  [Resources.Block, 'assets/sounds/block.wav'],
]);

export const musics = new Map<Resources, string>([
  [Resources.hub_bg, 'assets/music/hub/hub_bg.ogg'],
  [Resources.hub_ccl_flutes, 'assets/music/hub/hub_ccl_flutes.ogg'],
  [Resources.hub_cd_organ, 'assets/music/hub/hub_cd_organ.ogg'],
  [Resources.hub_cls_accordion, 'assets/music/hub/hub_cls_accordion.ogg'],
  [Resources.hub_cl_violin, 'assets/music/hub/hub_cl_violin.ogg'],
  [Resources.hub_c_piano, 'assets/music/hub/hub_c_piano.ogg'],
  [Resources.hub_d_chirp, 'assets/music/hub/hub_d_chirp.ogg'],
  [Resources.hub_sd_bells, 'assets/music/hub/hub_sd_bells.ogg'],
  [Resources.hub_s_harp, 'assets/music/hub/hub_s_harp.ogg'],
  [Resources.hub_celtic_clue, 'assets/music/hub/hub_celtic_clue.ogg'],

  [Resources.city_bg, 'assets/music/city/city_bg.ogg'],
  [Resources.city_A_melody_cello, 'assets/music/city/city_A-melody_cello.ogg'],
  [
    Resources.city_A_melody_marimba,
    'assets/music/city/city_A-melody_marimba.ogg',
  ],
  [
    Resources.city_A_melody_piano_f,
    'assets/music/city/city_A-melody_piano-f.ogg',
  ],
  [
    Resources.city_A_melody_piano_p,
    'assets/music/city/city_A-melody_piano-p.ogg',
  ],
  [Resources.city_A_melody_vibra, 'assets/music/city/city_A-melody_vibra.ogg'],
  [
    Resources.city_A_melody_violin,
    'assets/music/city/city_A-melody_violin.ogg',
  ],
  [Resources.city_chord_A, 'assets/music/city/city_chord-A.ogg'],
  [Resources.city_chord_F, 'assets/music/city/city_chord-F.ogg'],
  [Resources.city_chord_G, 'assets/music/city/city_chord-G.ogg'],
  [Resources.city_D_melody_cello, 'assets/music/city/city_D-melody_cello.ogg'],
  [Resources.city_D_melody_ethan, 'assets/music/city/city_D-melody_ethan.ogg'],
  [Resources.city_D_melody_piano, 'assets/music/city/city_D-melody_piano.ogg'],
  [
    Resources.city_D_melody_violins,
    'assets/music/city/city_D-melody_violins.ogg',
  ],
  [Resources.city_F_melody_ethan, 'assets/music/city/city_F-melody_ethan.ogg'],
  [
    Resources.city_F_melody_piano_1,
    'assets/music/city/city_F-melody_piano-1.ogg',
  ],
  [
    Resources.city_F_melody_piano_2,
    'assets/music/city/city_F-melody_piano-2.ogg',
  ],
  [
    Resources.city_F_melody_piano_3,
    'assets/music/city/city_F-melody_piano-3.ogg',
  ],
  [Resources.city_F_melody_vibra, 'assets/music/city/city_F-melody_vibra.ogg'],
  [Resources.city_marimba_bg_CA, 'assets/music/city/city_marimba-bg-CA.ogg'],
  [Resources.city_marimba_bg_F, 'assets/music/city/city_marimba-bg-F.ogg'],
  [Resources.city_marimba_bg_G, 'assets/music/city/city_marimba-bg-G.ogg'],
  [Resources.city_marimba_rtm_A, 'assets/music/city/city_marimba-rtm-A.ogg'],
  [
    Resources.city_marimba_rtm_F_2,
    'assets/music/city/city_marimba-rtm-F-2.ogg',
  ],
  [Resources.city_piano_rtm_F_2, 'assets/music/city/city_piano-rtm-F-2.ogg'],
  [Resources.city_piano_rtm_F, 'assets/music/city/city_piano-rtm-F.ogg'],
  [Resources.city_violin_bg_D, 'assets/music/city/city_violin-bg-D.ogg'],
  [Resources.city_violin_bg_F, 'assets/music/city/city_violin-bg-F.ogg'],
  [Resources.city_violin_bg_GA, 'assets/music/city/city_violin-bg-GA.ogg'],
  [Resources.city_violins_rtm_D, 'assets/music/city/city_violins-rtm-D.ogg'],
  [Resources.city_winds_E_p, 'assets/music/city/city_winds-E-p.ogg'],
  [Resources.city_winds_E_w, 'assets/music/city/city_winds-E-w.ogg'],
  [Resources.city_winds_FG, 'assets/music/city/city_winds-FG.ogg'],
  [Resources.city_winds_GE_p, 'assets/music/city/city_winds-GE-p.ogg'],
  [Resources.city_winds_GE_w, 'assets/music/city/city_winds-GE-w.ogg'],
  [
    Resources.city_xylophone_rtm_F_2,
    'assets/music/city/city_xylophone-rtm-F-2.ogg',
  ],
  [
    Resources.city_xylophone_rtm_F,
    'assets/music/city/city_xylophone-rtm-F.ogg',
  ],
  [Resources.city_xylo_rtm_A, 'assets/music/city/city_xylo-rtm-A.ogg'],

  [Resources.celtic_bg, 'assets/music/celtic/celtic_bg.ogg'],
  [Resources.celtic_A_bagpipe, 'assets/music/celtic/celtic_A_bagpipe.ogg'],
  [Resources.celtic_A_bombarde, 'assets/music/celtic/celtic_A_bombarde.ogg'],
  [Resources.celtic_A_perc, 'assets/music/celtic/celtic_A_perc.ogg'],
  [Resources.celtic_A_tenor, 'assets/music/celtic/celtic_A_tenor.ogg'],
  [Resources.celtic_A2_bagpipe, 'assets/music/celtic/celtic_A2_bagpipe.ogg'],
  [Resources.celtic_A2_bombarde, 'assets/music/celtic/celtic_A2_bombarde.ogg'],
  [Resources.celtic_A2_bourdons, 'assets/music/celtic/celtic_A2_bourdons.ogg'],
  [Resources.celtic_B_bagad, 'assets/music/celtic/celtic_B_bagad.ogg'],
  [Resources.celtic_B_bombarde, 'assets/music/celtic/celtic_B_bombarde.ogg'],
  [Resources.celtic_B_cornemuse, 'assets/music/celtic/celtic_B_cornemuse.ogg'],
  [Resources.celtic_B_tenor, 'assets/music/celtic/celtic_B_tenor.ogg'],
  [Resources.celtic_B_whistle, 'assets/music/celtic/celtic_B_whistle.ogg'],
  [Resources.celtic_B_guitar, 'assets/music/celtic/celtic_B_guitar.ogg'],
  [Resources.celtic_B_koto, 'assets/music/celtic/celtic_B_koto.ogg'],
  [Resources.celtic_B_violin, 'assets/music/celtic/celtic_B_violin.ogg'],
  [Resources.celtic_C_whistle, 'assets/music/celtic/celtic_C_whistle.ogg'],
  [
    Resources.celtic_C_guitar_chords,
    'assets/music/celtic/celtic_C_guitar_chords.ogg',
  ],
  [Resources.celtic_C_guitar, 'assets/music/celtic/celtic_C_guitar.ogg'],
  [Resources.celtic_C_harp, 'assets/music/celtic/celtic_C_harp.ogg'],
  [Resources.celtic_C_violin, 'assets/music/celtic/celtic_C_violin.ogg'],
  [
    Resources.celtic_C_whistle_high,
    'assets/music/celtic/celtic_C_whistle_high.ogg',
  ],
  [Resources.celtic_C_ocarina, 'assets/music/celtic/celtic_C_ocarina.ogg'],

  [Resources.sea_bg, 'assets/music/sea/sea_bg.ogg'],
  [Resources.sea_A_bass, 'assets/music/sea/sea_A_bass.ogg'],
  [Resources.sea_A_bells, 'assets/music/sea/sea_A_bells.ogg'],
  [Resources.sea_A_marimbas, 'assets/music/sea/sea_A_marimbas.ogg'],
  [Resources.sea_A_piano, 'assets/music/sea/sea_A_piano.ogg'],
  [Resources.sea_A_string, 'assets/music/sea/sea_A_string.ogg'],
  [Resources.sea_A_whistle, 'assets/music/sea/sea_A_whistle.ogg'],
  [Resources.sea_A_winds, 'assets/music/sea/sea_A_winds.ogg'],
  [Resources.sea_A_chimes, 'assets/music/sea/sea_A_chimes.ogg'],
  [Resources.sea_B_comet, 'assets/music/sea/sea_B_comet.ogg'],
  [Resources.sea_B_guitars, 'assets/music/sea/sea_B_guitars.ogg'],
  [Resources.sea_B_voyager, 'assets/music/sea/sea_B_voyager.ogg'],
  [Resources.sea_B_flute, 'assets/music/sea/sea_B_flute.ogg'],
  [Resources.sea_B_synth, 'assets/music/sea/sea_B_synth.ogg'],
  [Resources.sea_C_cornemuse, 'assets/music/sea/sea_C_cornemuse.ogg'],
  [Resources.sea_C_guitar, 'assets/music/sea/sea_C_guitar.ogg'],
  [Resources.sea_C_oboe, 'assets/music/sea/sea_C_oboe.ogg'],
  [Resources.sea_C_timpanis, 'assets/music/sea/sea_C_timpanis.ogg'],
  [Resources.sea_C_cymbals, 'assets/music/sea/sea_C_cymbals.ogg'],
  [Resources.sea_C_horn, 'assets/music/sea/sea_C_horn.ogg'],
  [Resources.sea_C_strings, 'assets/music/sea/sea_C_strings.ogg'],
  [Resources.sea_C_violin, 'assets/music/sea/sea_C_violin.ogg'],

  [Resources.desert_bg, 'assets/music/desert/desert_bg.ogg'],
  [Resources.desert_A_chords, 'assets/music/desert/desert_A_chords.ogg'],
  [Resources.desert_A_drums, 'assets/music/desert/desert_A_drums.ogg'],
  [Resources.desert_A_rhodes, 'assets/music/desert/desert_A_rhodes.ogg'],
  [Resources.desert_B_drum, 'assets/music/desert/desert_B_drum.ogg'],
  [Resources.desert_B_piano, 'assets/music/desert/desert_B_piano.ogg'],
  [Resources.desert_B_terje, 'assets/music/desert/desert_B_terje.ogg'],
  [Resources.desert_B_synth, 'assets/music/desert/desert_B_synth.ogg'],
  [Resources.desert_C_bells, 'assets/music/desert/desert_C_bells.ogg'],
  [Resources.desert_C_marimba, 'assets/music/desert/desert_C_marimba.ogg'],
  [Resources.desert_C_sax, 'assets/music/desert/desert_C_sax.ogg'],
  [Resources.desert_flute, 'assets/music/desert/desert_flute.ogg'],
]);
